export const GET_USERS = "GET_USERS";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const SAVE_QUESTION = "SAVE_QUESTION";
export const SAVE_QUESTION_ANSWER = "SAVE_QUESTION_ANSWER";
export const SAVE_USER_ANSWER = "SAVE_USER_ANSWER";
export const SET_AUTHED_USER = "SET_AUTHED_USER";
export const REGISTER_NEW_USER = "REGISTER_NEW_USER";
export const TEST_GET = "TEST_GET";
